HairExpress/Areas/Admin/Controllers/AdminUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HairExpress.Data;
using HairExpress.Models;
using Microsoft.AspNetCore.Mvc;

namespace HairExpress.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminUsersController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AdminUsersController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.ApplicationUsers.ToList());
        }

        //Get Edit
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || id.Trim().Length == 0)
            {
                return NotFound();
            }

            var userFromDb = await _db.ApplicationUsers.FindAsync(id);
            if (userFromDb == null)
            {
                return NotFound();
            }

            return View(userFromDb);
        }


        //Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, ApplicationUser applicationUser)
        {
            if (id != applicationUser.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                ApplicationUser userFromDb = _db.ApplicationUsers.Where(u => u.Id == id).FirstOrDefault();
                userFromDb.Name = applicationUser.Name;
                userFromDb.PhoneNumber = applicationUser.PhoneNumber;

                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(applicationUser);
        }


        //Get Delete
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || id.Trim().Length == 0)
            {
                return NotFound();
            }

            var userFromDb = await _db.ApplicationUsers.FindAsync(id);
            if (userFromDb == null)
            {
                return NotFound();
            }

            return View(userFromDb);
        }


        //Post Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(string id)
        {
            ApplicationUser userFromDb = _db.ApplicationUsers.Where(u => u.Id == id).FirstOrDefault();
            userFromDb.LockoutEnd = DateTime.Now.AddYears(1000);

            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

HairExpress/Areas/Admin/Controllers/HairTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HairExpress.Data;
using HairExpress.Models;
using Microsoft.AspNetCore.Mvc;

namespace HairExpress.Areas.Admin.Controllers
{
    //[Authorize(Roles = SD.SuperAdminEndUser)]
    [Area("Admin")]
    public class HairTypesController : Controller
    {

        private readonly ApplicationDbContext _db;

        public HairTypesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.HairTypes.ToList());
        }
        //GET Create Action Method
        public IActionResult Create()
        {
            return View();
        }

        //POST Create action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(HairType hairTypes)
        {
            if (ModelState.IsValid)
            {
                _db.Add(hairTypes);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hairTypes);
        }


        //GET Edit Action Method
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hairType = await _db.HairTypes.FindAsync(id);
            if (hairType == null)
            {
                return NotFound();
            }

            return View(hairType);
        }

        //POST Edit action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, HairType hairType)
        {
            if (id != hairType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _db.Update(hairType);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hairType);
        }

        //GET Details Action Method
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hairType = await _db.HairTypes.FindAsync(id);
            if (hairType == null)
            {
                return NotFound();
            }

            return View(hairType);
        }


        //GET Delete Action Method
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hairType = await _db.HairTypes.FindAsync(id);
            if (hairType == null)
            {
                return NotFound();
            }

            return View(hairType);
        }

        //POST Delete action Method
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var productTypes = await _db.HairTypes.FindAsync(id);
            _db.HairTypes.Remove(productTypes);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

HairExpress/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using HairExpress.Data;
using HairExpress.Models;
using HairExpress.Models.ViewModel;
using HairExpress.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HairExpress.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.SuperAdminEndUser)]
    [Area("Admin")]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly HostingEnvironment _hostingEnvironment;

        [BindProperty]
        public ProductsViewModel ProductsVM { get; set; }


        public ProductsController(ApplicationDbContext db, HostingEnvironment hostingEnvironment)
        {
            _db = db;
            _hostingEnvironment = hostingEnvironment;
            ProductsVM = new ProductsViewModel()
            {
                HairTypes = _db.HairTypes.ToList(),
                SpecialOffers = _db.SpecialOffers.ToList(),
                Products = new Product()
            };

        }


        public async Task<IActionResult> Index()
        {
            var products = _db.Products.Include(m => m.HairTypes).Include(m => m.SpecialOffers);
            return View(await products.ToListAsync());
        }

        //Get : Products Create
        public IActionResult Create()
        {
            return View(ProductsVM);
        }

        //Post : Products Create
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePOST()
        {
            if (!ModelState.IsValid)
            {
                return View(ProductsVM);
            }

            _db.Products.Add(ProductsVM.Products);
            await _db.SaveChangesAsync();

            //Image being saved

            string webRootPath = _hostingEnvironment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            var productsFromDb = _db.Products.Find(ProductsVM.Products.Id);

            if (files.Count != 0)
            {
                //Image has been uploaded
                var uploads = Path.Combine(webRootPath, SD.ImageFolder);
                var extension = Path.GetExtension(files[0].FileName);

                using (var filestream = new FileStream(Path.Combine(uploads, ProductsVM.Products.Id + extension), FileMode.Create))
                {
                    files[0].CopyTo(filestream);
                }
                productsFromDb.Image = @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + extension;
            }
            else
            {
                //when user does not upload image
                var uploads = Path.Combine(webRootPath, SD.ImageFolder + @"\" + SD.DefaultProductImage);
                System.IO.File.Copy(uploads, webRootPath + @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + ".png");
                productsFromDb.Image = @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + ".png";
            }
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }



        //GET : Edit
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ProductsVM.Products = await _db.Products.Include(m => m.SpecialOffers).Include(m => m.HairTypes).SingleOrDefaultAsync(m => m.Id == id);

            if (ProductsVM.Products == null)
            {
                return NotFound();
            }

            return View(ProductsVM);
        }


        //Post : Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id)
        {
            if (ModelState.IsValid)
            {
                string webRootPath = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                var productFromDb = _db.Products.Where(m => m.Id == ProductsVM.Products.Id).FirstOrDefault();

                if (files.Count > 0 && files[0] != null)
                {
                    //if user uploads a new image
                    var uploads = Path.Combine(webRootPath, SD.ImageFolder);
                    var extension_new = Path.GetExtension(files[0].FileName);
                    var extension_old = Path.GetExtension(productFromDb.Image);

                    if (System.IO.File.Exists(Path.Combine(uploads, ProductsVM.Products.Id + extension_old)))
                    {
                        System.IO.File.Delete(Path.Combine(uploads, ProductsVM.Products.Id + extension_old));
                    }
                    using (var filestream = new FileStream(Path.Combine(uploads, ProductsVM.Products.Id + extension_new), FileMode.Create))
                    {
                        files[0].CopyTo(filestream);
                    }
                    ProductsVM.Products.Image = @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + extension_new;
                }

                if (ProductsVM.Products.Image != null)
                {
                    productFromDb.Image = ProductsVM.Products.Image;
                }

                productFromDb.Name = ProductsVM.Products.Name;
                productFromDb.Price = ProductsVM.Products.Price;
                productFromDb.Available = ProductsVM.Products.Available;
                productFromDb.HairTypeId = ProductsVM.Products.HairTypeId;
                productFromDb.SpecialOfferId = ProductsVM.Products.SpecialOfferId;
                productFromDb.ShadeColor = ProductsVM.Products.ShadeColor;
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(ProductsVM);
        }


        //GET : Details
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ProductsVM.Products = await _db.Products.Include(m => m.SpecialOffers).Include(m => m.HairTypes).SingleOrDefaultAsync(m => m.Id == id);

            if (ProductsVM.Products == null)
            {
                return NotFound();
            }

            return View(ProductsVM);
        }

        //GET : Delete
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ProductsVM.Products = await _db.Products.Include(m => m.SpecialOffers).Include(m => m.HairTypes).SingleOrDefaultAsync(m => m.Id == id);

            if (ProductsVM.Products == null)
            {
                return NotFound();
            }

            return View(ProductsVM);
        }

        //POST : Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            string webRootPath = _hostingEnvironment.WebRootPath;
            Product products = await _db.Products.FindAsync(id);

            if (products == null)
            {
                return NotFound();
            }
            else
            {
                var uploads = Path.Combine(webRootPath, SD.ImageFolder);
                var extension = Path.GetExtension(products.Image);

                if (System.IO.File.Exists(Path.Combine(uploads, products.Id + extension)))
                {
                    System.IO.File.Delete(Path.Combine(uploads, products.Id + extension));
                }
                _db.Products.Remove(products);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
        }

    }
}

HairExpress/Areas/Admin/Controllers/SpecialOffersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HairExpress.Data;
using HairExpress.Models;
using Microsoft.AspNetCore.Mvc;

namespace HairExpress.Areas.Admin.Controllers
{
    //[Authorize(Roles = SD.SuperAdminEndUser)]
    [Area("Admin")]
    public class SpecialOffersController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SpecialOffersController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.SpecialOffers.ToList());
        }
        //GET Create Action Method
        public IActionResult Create()
        {
            return View();
        }

        //POST Create action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpecialOffer specialOffer)
        {
            if (ModelState.IsValid)
            {
                _db.Add(specialOffer);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(specialOffer);
        }


        //GET Edit Action Method
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specialOffer = await _db.SpecialOffers.FindAsync(id);
            if (specialOffer == null)
            {
                return NotFound();
            }

            return View(specialOffer);
        }

        //POST Edit action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, SpecialOffer specialOffer)
        {
            if (id != specialOffer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _db.Update(specialOffer);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(specialOffer);
        }

        //GET Details Action Method
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specialOffer = await _db.SpecialOffers.FindAsync(id);
            if (specialOffer == null)
            {
                return NotFound();
            }

            return View(specialOffer);
        }


        //GET Delete Action Method
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specialOffer = await _db.SpecialOffers.FindAsync(id);
            if (specialOffer == null)
            {
                return NotFound();
            }

            return View(specialOffer);
        }

        //POST Delete action Method
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var specialTags = await _db.SpecialOffers.FindAsync(id);
            _db.SpecialOffers.Remove(specialTags);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

HairExpress/Views/Shared/_AppointmentCustomerDetails.cshtml
@model HairExpress.Models.Appointments
<h4 class="text-success">Appointment Details</h4>
<div style="height:100px; background-color:aliceblue" class="container border">
    <div class="col-12">
        <div class="row" style="padding-top:10px;">
            <div class="col-2">
                Full Name
            </div>
            <div class="col-3">
                <input asp-for="@Model.CustomerName" readonly class="form-control" />
            </div>
            <div class="col-2">
            </div>
            <div class="col-2">
                Email
            </div>
            <div class="col-3">
                <input asp-for="@Model.CustomerEmail" readonly class="form-control" />
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="row" style="padding-top:10px;">
            <div class="col-2">
                Phone Number
            </div>
            <div class="col-3">
                <input asp-for="@Model.CustomerPhoneNumber" readonly class="form-control" />
            </div>
            <div class="col-2">
            </div>
            <div class="col-2">
                Appointment Date
            </div>
            <div class="col-3">
                <input asp-for="@Model.AppointmentDate" readonly class="form-control" />
            </div>
        </div>
    </div>
</div>

HairExpress/Views/Shared/_AppointmentProductDetails.cshtml
@model List<HairExpress.Models.Product>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@if (Model.Count > 0)
{
    <table class="table table-striped" width="100%">
        <tr class="table-info">
            <th style="text-align:center; width:20%"></th>
            <th style="text-align:center;">
                <label asp-for="@Model.FirstOrDefault().Name"></label>
            </th>
            <th style="text-align:center;">
                <label asp-for="@Model.FirstOrDefault().Price"></label>
            </th>
            <th style="text-align:center;">
                <label asp-for="@Model.FirstOrDefault().ShadeColor"></label>
            </th>
            <th style="text-align:center;">
                <label asp-for="@Model.FirstOrDefault().HairTypes.Name"></label>
            </th>
            <th style="text-align:center;"></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr style="padding:50px;">
                <td>
                    <a asp-area="Customer" asp-controller="Home" asp-action="Details" asp-route-id="@item.Id">
                        <img src="@item.Image" width="100%" style="margin:auto; display:block; border-radius:5px; border:1px solid #bbb9b9;" />
                    </a>
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(c => item.Name)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(c => item.Price)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(c => item.ShadeColor)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(c => item.HairTypes.Name)
                </td>
                <td style="text-align:center"></td>
            </tr>

        }
    </table>
}
else
{
    <div>No items added to the shopping cart...</div>
}

HairExpress/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using HairExpress.Extensions
@using HairExpress.Utility
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HairExpress</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">

        <a asp-area="Customer" asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="~/images/logo.PNG" width="50px" height="40px" alt="company logo" /> Classic Barbers</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">MY NAME</span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                @if (User.IsInRole(SD.SuperAdminEndUser))
                {
                    <li class="nav-item "><a class="nav-link text-white hover_effect" asp-area="Admin" asp-controller="HairTypes" asp-action="Index">Hair Types</a></li>
                    <li class="nav-item "><a class="nav-link text-white hover_effect" asp-area="Admin" asp-controller="SpecialOffers" asp-action="Index">Special Offers</a></li>
                    <li class="nav-item "><a class="nav-link text-white hover_effect" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a></li>
                    <li class="nav-item "><a class="nav-link text-white hover_effect" asp-area="Admin" asp-controller="AdminUsers" asp-action="Index">Admin Users</a></li>
                }
                @if (User.IsInRole(SD.SuperAdminEndUser) || User.IsInRole(SD.AdminEndUser))
                {
                    <li class="nav-item"><a class="nav-link text-white hover_effect" asp-area="Admin" asp-controller="Appointments" asp-action="Index">Appointments</a></li>
                }

                    @if (HttpContextAccessor.HttpContext.Session.Get<List<Guid>>("ssShoppingCart") != null)
                    {
                        <li style="color:white">
                            <a asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
                                <i class="fas fa-shopping-cart"></i> &nbsp;
                                @{
                                    var count = HttpContextAccessor.HttpContext.Session.Get<List<Guid>>("ssShoppingCart").Count;
                                }
                                (@count)
                            </a>
                        </li>

                    }
                    else
                    {
                        <li style="color:white">
                            <a asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
                                <i class="fas fa-shopping-cart"></i> &nbsp;

                                (0)
                            </a>
                        </li>

                    }




                </ul>

            <ul class="nav justify-content-end">
                <li class="nav-item" style="top: 17.5em;">
                    <partial name="_LoginPartial" />
                </li>
            </ul>
        </div>
    </nav>


    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
    </div>
    <div class="footer container-fluid ">
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year <img src="~/images/logo.png" width="50px" height="40px" id="logo-footer" />Classic Beautifier</p>*@
            <!-- Footer Links -->
            <!-- Footer Links -->
            <div class="footer-contact mt-5 d-flex justify-content-around flex-wrap">
                <!-- single contact -->
                <div class="text-capitalize text-green">
                    <span class="footer-icon mr-2">
                        <i class="fas fa-map"></i>
                    </span>
                    23 Moira Street, Cardiff CF24 0EQ
                </div>
                <!-- end of single contact -->
                <!-- single contact -->
                <div class="text-capitalize text-green">
                    <span class="footer-icon mr-2">
                        <i class="fas fa-phone"></i>
                    </span>
                    phone : + (44) 744 619 3908
                </div>
                <!-- end of single contact -->
                <!-- single contact -->
                <div class="text-lowercase text-green">
                    <span class="footer-icon mr-2">
                        <i class="fas fa-envelope"></i>
                    </span>
                    email : seakou2@email.com
                </div>
                <!-- end of single contact -->
            </div>
            <!-- Copyright -->
            <div class="footer-copyright text-center py-3 text-green">
                <p>&copy; @DateTime.Now.Year <img src="~/images/logo.png" width="50px" height="40px" id="logo-footer" />Classic Beautifier</p>
            </div>
            <!-- Copyright -->

        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/jquery-ui.js" asp-append-version="true"></script>
        <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/jquery-ui.js" asp-append-version="true"></script>
        <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

HairExpress/Views/Shared/_TableButtonPartial.cshtml
@model Guid
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width:150px">
    <div class="btn-group" role="group">
        <a type="button" class="btn btn-primary" href="@Url.Action("Edit/"+Model)">
            <i class="fas fa-edit"></i>
        </a>
        <a type="button" class="btn btn-success" href="@Url.Action("Details/"+Model)">
            <i class="far fa-list-alt"></i>
        </a>
        <a type="button" class="btn btn-danger" href="@Url.Action("Delete/"+Model)">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>